services:
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    restart: unless-stopped
    hostname: kafka
    ports:
      - "9092:9092"     # untuk host
      - "29092:29092"   # untuk container lain di dalam docker network
      - "9094:9094"     # SASL_PLAINTEXT
    networks:
      - kafka_network
    environment:
      CLUSTER_ID: "kraft-cluster"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9095

      # ===== Listeners =====
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,SASL_PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092,SASL_PLAINTEXT://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # ===== SASL configs =====
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"

      # ===== Log dirs =====
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # ===== Topic auto create =====
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - ./kafka:/tmp/kraft-combined-logs
      - ./secrets:/etc/kafka/secrets
   
  akhq:
    image: tchiotludo/akhq:0.24.0
    container_name: akhq
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - kafka_network
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: kafka:29092
          security:
            enabled: false
    depends_on:
      - kafka

networks:
  kafka_network:
    external: true
